version: '3'
services:
  smashing-app:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    volumes:
      - ./:/app/my-project
    ports:
      - '3030:3030'
    environment:
      - WEATHER_KEY=${WEATHER_KEY}
    entrypoint: [ 'smashing', 'start' ]